services:
  gh-pages:
    build:
      context: https://gist.github.com/0b345a2656abe079c322ad0a90a32c61.git
      dockerfile: Dockerfile.alpine
    ports:
      - "4000:4000"
    volumes:
      - "./:/src/site"